Lots of changes, i.a., X11/Openbox->Wayland/sway

diff --git a/home/DOTbashrc b/home/DOTbashrc
--- a/home/DOTbashrc
+++ b/home/DOTbashrc
@@ -1,120 +1,172 @@
-#
-# ~/.bashrc
-#
-
 # If not running interactively, don't do anything
 [[ $- != *i* ]] && return
 
-# No bash history file:
-export HISTFILE=
-
-# No less history file, let colours through less, colour man pages:
-export LESSHISTFILE="-"
-export LESS="--RAW-CONTROL-CHARS"
-export LESS_TERMCAP_mb=$'\E[01;31m'
-export LESS_TERMCAP_md=$'\E[01;34m'
-export LESS_TERMCAP_me=$'\E[0m'
-export LESS_TERMCAP_us=$'\E[04;34m'
-export LESS_TERMCAP_ue=$'\E[0m'
-export LESS_TERMCAP_so=$'\E[33m'
-export LESS_TERMCAP_se=$'\E[0m'
-
-# Defaults and colours for grep:
-export GREP_COLORS="mt=07;01;33:fn=35:ln=36:bn=36:se=34"
-
-# Standard programs:
-export EDITOR="vim"
-export PAGER="less"
-export BROWSER="chromium"
-
-# Bash won't get SIGWINCH if another process is in the foreground.
-# Enable checkwinsize so that bash will check the terminal size when
-# it regains control.
-# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
+# Various bash-specific settings:
+# ===============================
 shopt -s checkwinsize
-
-# Enable history appending instead of overwriting.
 shopt -s histappend
+unset HISTFILE
 
-# Set colorful PS1 only on colorful terminals.
-# dircolors --print-database uses its own built-in database
-# instead of using /etc/DIR_COLORS. Try to use the external file
-# first to take advantage of user additions. Use internal bash
-# globbing instead of external grep binary.
-# https://wiki.archlinux.org/index.php/Color_Bash_Prompt
-
-# sanitize TERM:
-safe_term=${TERM//[^[:alnum:]]/?}
-match_lhs=""
-
-[[ -f ~/.dir_colors ]] && match_lhs="${match_lhs}$(<~/.dir_colors)"
-[[ -f /etc/DIR_COLORS ]] && match_lhs="${match_lhs}$(</etc/DIR_COLORS)"
-[[ -z ${match_lhs} ]] \
-    && type -P dircolors >/dev/null \
-    && match_lhs=$(dircolors --print-database)
-
-if [[ $'\n'${match_lhs} == *$'\n'"TERM "${safe_term}* ]] ; then
-    # we have colors :-)
-
-    # Enable colors for ls, etc. Prefer ~/.dir_colors
-    if type -P dircolors >/dev/null ; then
-        if [[ -f ~/.dir_colors ]] ; then
-            eval $(dircolors -b ~/.dir_colors)
-        elif [[ -f /etc/DIR_COLORS ]] ; then
-            eval $(dircolors -b /etc/DIR_COLORS)
-        fi
-    fi
-
-    ret_nok='\[\e[1;31m\]'  # red
-    ret_ok='\[\e[1;32m\]'   # green
-    if [[ ${EUID} == 0 ]]; then
-        sq_c='\[\e[1;31m\]' # red
-        un_c='\[\e[1;31m\]' # red
-    else
-        sq_c='\[\e[1;37m\]' # white
-        un_c='\[\e[1;36m\]' # cyan
-    fi
-    at_c='\[\e[0;37m\]'     # grey
-    ho_c='\[\e[1;36m\]'     # cyan
-    ti_c='\[\e[1;33m\]'     # yellow
-    ve_c='\[\e[1;35m\]'     # magenta
-    di_c='\[\e[1;34m\]'     # blue
-    end_c='\[\e[0m\]'
-    PS1="$sq_c[\$(ec=\$?; [[ \$ec != 0 ]] && echo \"$ret_nok\$ec\" || echo \"$ret_ok\$ec\")$sq_c]—[$un_c\u$at_c@$ho_c\h$sq_c]—[$ti_c\t$sq_c]\$([[ -n "\$VIRTUAL_ENV" ]] && (v=\${VIRTUAL_ENV##*/}; echo \"—[$ve_c\$v$sq_c]\"))—[$di_c\w$sq_c]\n$sq_c\\\$ $end_c"
-    unset ret_nok ret_ok sq_c un_c at_c ho_c ti_c ve_c di_c end_c
-    export VIRTUAL_ENV_DISABLE_PROMPT=1
-
-    alias ls="ls --color=auto --classify"
-    alias grep="grep --color=auto"
-    alias dmesg="dmesg --color=auto --human"
-    alias diff="colordiff"
+# Set colors if on virtual console:
+# =================================
+if [ "$TERM" = "linux" ]; then
+    echo -en "\\e]P0000000"  # black
+    echo -en "\\e]P1DB6F6F"  # dark red
+    echo -en "\\e]P26FDB6F"  # dark green
+    echo -en "\\e]P3B7B74B"  # dark yellow
+    echo -en "\\e]P46F6FDB"  # dark blue
+    echo -en "\\e]P5B74BB7"  # dark magenta
+    echo -en "\\e]P64BB7B7"  # dark cyan
+    echo -en "\\e]P7939393"  # dark gray
+    echo -en "\\e]P8242424"  # very dark gray
+    echo -en "\\e]P9FF9393"  # light red
+    echo -en "\\e]PA93FF93"  # light green
+    echo -en "\\e]PBDBDB6F"  # light yellow
+    echo -en "\\e]PC9393FF"  # light blue
+    echo -en "\\e]PDDB6FDB"  # light magenta
+    echo -en "\\e]PE6FDBDB"  # light cyan
+    echo -en "\\e]PFB7B7B7"  # white – light gray
 fi
 
-# Try to keep environment pollution down, EPA loves us.
-unset safe_term match_lhs
+# Standard programs:
+# ==================
+# Arch packages: vim, less
+# Ubuntu packages: …
+# Termux packages: …
+export EDITOR="vim"
+export PAGER="less"
 
-# Alias for sudo to preserve environment and expand aliases:
-alias sudo='sudo -E '
+# Settings for specific programs (alphabetically):
+# ================================================
+# Arch packages: coreutils, diffutils, grep, less, man-db, util-linux
+# Ubuntu packages: …
+# Termux packages: …
+alias diff="diff --color=always"
 
-# Try to enable "Command not found" hook ("pacman -S pkgfile" to install).
-# https://wiki.archlinux.org/index.php/Bash#The_.22command_not_found.22_hook
-[ -r /usr/share/doc/pkgfile/command-not-found.bash ] &&
-    . /usr/share/doc/pkgfile/command-not-found.bash
+alias dmesg="dmesg --human --color=always"
 
-# Aliases for xrandr:
-alias xrandr-hdmi='xrandr --output LVDS1 --auto --output HDMI1 --auto\
-    --right-of LVDS1 && eval $(cat ~/.fehbg)'
-alias xrandr-vga='xrandr --output LVDS1 --auto --output VGA1 --auto\
-    --right-of LVDS1 && eval $(cat ~/.fehbg)'
-alias xrandr-off='xrandr --output LVDS1 --auto --output HDMI1 --off\
-    --output VGA1 --off && eval $(cat ~/.fehbg)'
+alias grep="grep --color=always"
+export GREP_COLORS="mt=07;33:fn=35:ln=36:bn=36:se=34"
+# mt – matching text: reverse dark yellow
+# fn – file name: dark magenta
+# ln – line number: dark cyan
+# bn – byte number: dark cyan
+# se – separators: dark blue
 
-# Aliases for Freifunk-APs:
-alias ssh-ff-01='ssh root@2a03:2260:114:5:16cc:20ff:fe8a:45f0'
-alias ssh-ff-02='ssh root@2a03:2260:114:5:8616:f9ff:fe48:fd2e'
-alias ssh-ff-03='ssh root@2a03:2260:114:5:16cc:20ff:fe63:1c2'
+export LESS="--RAW-CONTROL-CHARS --LONG-PROMPT"
+export LESSHISTFILE="-"
+export LESS_TERMCAP_mb=$'\E[31m'      # blink start: dark red
+export LESS_TERMCAP_md=$'\E[36m'      # bold start: dark cyan
+export LESS_TERMCAP_me=$'\E[0m'       # blink, bold, underline end
+export LESS_TERMCAP_us=$'\E[34m'      # underline start: dark blue
+export LESS_TERMCAP_ue=$'\E[0m'       # underline end
+export LESS_TERMCAP_so=$'\E[7;33m'    # standout start: reverse dark yellow
+export LESS_TERMCAP_se=$'\E[0m'       # standout end
 
-# Settings for Python virtualenvwrapper:
-export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
-export WORKON_HOME=~/PythonEnvs
-source /usr/bin/virtualenvwrapper.sh
+alias ls="ls --classify --color=always"
+export LS_COLORS="rs=0:di=34:st=34:ow=34:tw=34:ln=36:or=30;46:mi=30;41:ex=32:su=31:sg=31:ca=32:pi=33:so=33:do=33:bd=33:cd=33"
+# rs – reset
+# di – directory: dark blue
+# st – sticky: dark blue
+# ow – other writable: dark blue
+# tw – sticky other writable: dark blue
+# ln – symbolic link: dark cyan
+# or – orphan link: reverse dark cyan
+# mi – missing: reverse dark red
+# ex - executable: dark green
+# su – setuid: dark red
+# sg – setgid: dark red
+# ca - dark green
+# pi – pipe: reverse dark yellow
+# so – socket: reverse dark yellow
+# do – door: reverse dark yellow
+# bd – block device: reverse dark yellow
+# cd – character device: reverse dark yellow
+
+export MANPAGER="less --squeeze-blank-lines --LONG-PROMPT +Gg"
+
+if [ "$TERM" = "xterm-termite" ]
+then
+    alias ssh="TERM=xterm-256color ssh"
+fi
+
+alias sudo="sudo -E "
+
+# Prompt:
+# =======
+# Colours for prompt lines, return values, time, user, host and workdir:
+sq_c='\[\e[1;37m\]'     # light gray
+ret_nok='\[\e[1;31m\]'  # light red
+ret_ok='\[\e[1;32m\]'   # light green
+ti_c='\[\e[1;33m\]'     # light yellow
+uh_c='\[\e[1;36m\]'     # light cyan
+di_c='\[\e[1;35m\]'     # light magenta
+end_c='\[\e[0m\]'
+# Function for virtual environment:
+ps1_venv() {
+    if [ -n "$VIRTUAL_ENV" ]
+    then
+        local venv="${VIRTUAL_ENV##*/}"
+        if [ "$venv" = "venv" ]
+        then
+            local path="${VIRTUAL_ENV%/*}"
+            venv="${path##*/}/$venv"
+        fi
+        echo -e "-[\001\e[1;34m\002v:$venv\001\e[1;37m\002]"  # light blue
+    fi
+}
+export VIRTUAL_ENV_DISABLE_PROMPT=1
+# Prompt command for shortened workdir:
+PROMPT_COMMAND='ps1_path=$(sed "s:\([^/\.]\)[^/]*/:\1/:g" <<< ${PWD/#$HOME/\~})'
+# Function for fossil checkout state:
+if [ -x "$(command -v fossil)" ]
+then
+    ps1_fossil() {
+        local branch=$(fossil branch 2> /dev/null | sed -n 's/* \(.*\)/\1/p')
+        if [ -n "$branch" ]
+        then
+            local color="1;32m"  # light green
+            if [ -n "$(fossil extras)" ]
+            then
+                color="1;33m"    # light yellow
+            fi
+            if [ -n "$(fossil changes)" ]
+            then
+                color="1;31m"    # light red
+            fi
+            echo -e "-[\001\e[$color\002f:$branch\001\e[1;37m\002]"
+        fi
+    }
+else
+    ps1_fossil() {
+        return
+    }
+fi
+# Function for git checkout state:
+if [ -x "$(command -v git)" ]
+then
+    ps1_git() {
+        local branch=$(git branch 2> /dev/null | sed -n 's/* \(.*\)/\1/p')
+        if [ -n "$branch" ]
+        then
+            local color="1;32m"  # light green
+            local changes=$(git status --porcelain)
+            if [ -n "$changes" ]
+            then
+                color="1;33m"    # light yellow
+            fi
+            if [ -n "$(grep -v '^??' <<< $changes)" ]
+            then
+                color="1;31m"    # light red
+            fi
+            echo -e "-[\001\e[$color\002g:$branch\001\e[1;37m\002]"
+        fi
+    }
+else
+    ps1_git() {
+        return
+    }
+fi
+# And finally the whole prompt:
+PS1="$sq_c[\$(ec=\$?; [[ \$ec != 0 ]] && echo \"$ret_nok\$ec\" || echo \"$ret_ok\$ec\")$sq_c]-[$ti_c\t$sq_c]-[$uh_c\u@\h$sq_c]\$(ps1_venv)-[$di_c\$ps1_path$sq_c]\$(ps1_fossil)\$(ps1_git)\n$sq_c\\\$ $end_c"
+unset sq_c ret_nok ret_ok ti_c uh_c di_c end_c
